### ISSUE TITLE
ASP.NET Core - New database tutorial error

### ISSUE THREAD

**Issue by Klipi** [aspnet/EntityFramework.Docs#346]
I'm following the tutorial here: https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db up to the point where I need to run the first migration:

```
PM> Add-Migration MyFirstMigration
Unable to resolve startup project 'Microsoft.PowerShell.Core\FileSystem::\\mac\home\documents\visual studio 2017\Projects\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb.csproj'.
To undo this action, use Remove-Migration.
Add-Migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null character.
Parameter name: basePath"
At line:1 char:1
+ Add-Migration MyFirstMigration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration
```

I'm running Visual Studio 2017 RC1 under a Win10 VM in Parallels, so that might be the cause of some issues. However I have no idea on how to start to debug this, as I'm quite new to the .NET Core world and Entity Framework.

**Comment by rowanmiller** [comment]
@Klipi you would need to upgrade to RC3, I will call that our specifically in the walkthrough.

**Comment by Klipi** [comment]
@rowanmiller, Sorry, looks like I typoed RC as RC1. The actual version is VisualStudio/15.0.0-RC.3+26127.3, so if I'm reading this correctly, RC3?

**Comment by rowanmiller** [comment]
Looks the same, I used 26127.0 to write and test the tutorial. @bricelam any thoughts on this one?

**Comment by bricelam** [comment]
What are the results of typing the following commands inside PMC?
```ps1
$DTE.Solution.SolutionBuild.StartupProjects
$DTE.Solution.Properties.Item('Path').Value
```

**Comment by bricelam** [comment]
I'm shocked Windows is getting paths like this: `\\mac\home`. I'm sure they're breaking all kinds of assumptions in PowerShell, Visual Studio, and Windows code.

**Comment by bricelam** [comment]
Actually, it's probably trying to run directly from a virtual network file share back to the host OS. I'm not sure if we should try and support this...

Are the PowerShell commands the only thing braking? Do they work if you move the project to somewhere under `C:\` (or any other drive)?

**Comment by Klipi** [comment]
```
PM> $DTE.Solution.SolutionBuild.StartupProjects
EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb.csproj
PM> $DTE.Solution.Properties.Item('Path').Value
\\mac\home\Documents\Visual Studio 2017\Projects\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb.sln
```
I'll try to redo the tutorial under C:\ and see what happens. Not sure if anything else is breaking, been away from Windows and VS for a couple of years. A quick HelloWorld-type web app works nicely and I was even able to publish it to Azure without a hitch. Trying to add the database layer (and EF along it) is the first I'm running into trouble.

**Comment by rowanmiller** [comment]
Moved over to the runtime repo: https://github.com/aspnet/EntityFramework/issues/7540

**Comment by bricelam** [comment]
> A quick HelloWorld-type web app works nicely

Yeah, we should support it then.

**Comment by yavargraphic** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/26131576/25782469/d982f3f6-3360-11e7-943a-52111ee60d97.jpg)
plase help red line?

**Comment by divega** [comment]
@yavargraphic can you please create a new issue in the product repo (gitub.com/aspnet/entityframework/issues/ for EF Core)? please include the full repro information relevant to the issue when you do so.

**Comment by JulienM28** [comment]
I have the same problem with last version of VS 2017 and any version of .net core and tools

Someone have a solution?

**Comment by d1mnewz** [comment]
Same issue with last VS17 version. 
ASPNETCore + EFCore, last release versions from nuget.
[what is happening](http://g.recordit.co/ikEw64EfSH.gif)

**Comment by wallone** [comment]
Klipi or anyone else,

I am having the same exact problem and I was wondering if the solution was found. Thanks for your help.

**PM> Add-Migration MyFirstMigration
Unable to resolve startup project 'Microsoft.PowerShell.Core\FileSystem::\\mac\home\documents\visual studio 2017\Projects\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb.csproj'.
To undo this action, use Remove-Migration.
Add-Migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null character.
Parameter name: basePath"
At line:1 char:1
+ Add-Migration MyFirstMigration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration**

**Comment by Klipi** [comment]
@wallone, you can track the progress on the issue here: https://github.com/aspnet/EntityFramework/issues/7540

I ended up working around it and just have the project under C:/ in the VM. Apparently the virtual drive path causes some headaches in the tooling.

**Comment by JulienM28** [comment]
I found a solution to this issue:
Cretae a fresh new project and paste your files into it.

The problem seems coming from project files.

My project started some months ago with the early stages of .Net core. 
I think there's some old crappy stuff in this kind of projects.

With a new one, there's no more issue.

**Comment by consule** [comment]
I have  the same problem... 

Add-Migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with 
the null character.
Parameter name: basePath"
At line:1 char:1
+ Add-Migration Initialt
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration

**Comment by mhouston100** [comment]
I'm just following the tutorial also. Just thought I would chime in to say that I'm hitting this issue do to redirected folders it looks like. 

`Unable to resolve startup project 'Microsoft.PowerShell.Core\FileSystem::\\fs-win-v02\redirectedfolders\matthewh\documents\visual studio 2017\Projects\MvcMovie\MvcMovie\MvcMovie.csproj'.`

Latest updated VS2017

**Comment by bricelam** [comment]
What version of Microsoft.EntityFrameworkCore.Tools? This was fixed in 2.0.0-preview2-final.

**Comment by dvdobrovolskiy** [comment]
**Same**

PM> add-migration Amount
To undo this action, use Remove-Migration.
add-migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null ch
aracter.
Parameter name: basePath"
At line:1 char:1
+ add-migration Amount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration

**Comment by rsandhumcr** [comment]
I had the same problem with .net core 1.1 .
I solved my problem by creating a console app in my solution.
Made a reference to the project containing my written db context in the console app.
Executed the 'Add-Migration Initial' with success.

**Comment by anis1011** [comment]
@rsandhumcr I also have the same problem, would you  please elaborate your solution ? I made the console project as startup project and reference the main project from console application but still cannot run the Add-Migration Initial
